/* Generated by scripts/build-player-list.mjs — do not edit by hand.
   Source: data/stats.json, league 19719, 2026-08-13T23:16:20.131Z
   16 teams, 80 players. */
window.TI_PLAYERS = [
 {
  "teamId": 9467224,
  "teamName": "Aurora Gaming",
  "players": [
   {
    "accountId": 124801257,
    "name": "Nightfall",
    "pos": 1
   },
   {
    "accountId": 301750126,
    "name": "Mikoto",
    "pos": 2
   },
   {
    "accountId": 126842529,
    "name": "Ws`",
    "pos": 3
   },
   {
    "accountId": 256156323,
    "name": "Mira",
    "pos": 4
   },
   {
    "accountId": 320219866,
    "name": "kaori",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 8255888,
  "teamName": "BoomBoys",
  "players": [
   {
    "accountId": 172099728,
    "name": "Kiritych~",
    "pos": 1
   },
   {
    "accountId": 480412663,
    "name": "gpk~",
    "pos": 2
   },
   {
    "accountId": 165564598,
    "name": "MieRo",
    "pos": 3
   },
   {
    "accountId": 317880638,
    "name": "Save-",
    "pos": 4
   },
   {
    "accountId": 196878136,
    "name": "Kataomi`",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 9964962,
  "teamName": "GamerLegion",
  "players": [
   {
    "accountId": 206642367,
    "name": "Ghost",
    "pos": 1
   },
   {
    "accountId": 154974246,
    "name": "RCY",
    "pos": 2
   },
   {
    "accountId": 160119017,
    "name": "Fayde",
    "pos": 3
   },
   {
    "accountId": 90423751,
    "name": "Bignum",
    "pos": 4
   },
   {
    "accountId": 191362875,
    "name": "Speeed",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 10149530,
  "teamName": "HULIGANI",
  "players": [
   {
    "accountId": 320017600,
    "name": "ssnovv1",
    "pos": 1
   },
   {
    "accountId": 140251702,
    "name": "Mirage`雨",
    "pos": 2
   },
   {
    "accountId": 92487440,
    "name": "Corrupted",
    "pos": 3
   },
   {
    "accountId": 145065875,
    "name": "sayuw",
    "pos": 4
   },
   {
    "accountId": 123787715,
    "name": "RESPECT",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 10150413,
  "teamName": "Iron Wing",
  "players": [
   {
    "accountId": 331855530,
    "name": "Pure",
    "pos": 1
   },
   {
    "accountId": 93618577,
    "name": "bzm",
    "pos": 2
   },
   {
    "accountId": 86698277,
    "name": "33",
    "pos": 3
   },
   {
    "accountId": 346412363,
    "name": "Ari",
    "pos": 4
   },
   {
    "accountId": 136829091,
    "name": "Whitemon",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 10150538,
  "teamName": "LGD Gaming",
  "players": [
   {
    "accountId": 177203952,
    "name": "Yuma",
    "pos": 1
   },
   {
    "accountId": 94054712,
    "name": "Topson",
    "pos": 2
   },
   {
    "accountId": 292921272,
    "name": "Wisper",
    "pos": 3
   },
   {
    "accountId": 105045291,
    "name": "Thiolicor",
    "pos": 4
   },
   {
    "accountId": 81306398,
    "name": "KingJungles",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 10136357,
  "teamName": "Nigma Galaxy ",
  "players": [
   {
    "accountId": 111620041,
    "name": "SumaiL-",
    "pos": 1
   },
   {
    "accountId": 210053851,
    "name": "lorenof",
    "pos": 2
   },
   {
    "accountId": 138880576,
    "name": "Davai",
    "pos": 3
   },
   {
    "accountId": 152168157,
    "name": "OmaR",
    "pos": 4
   },
   {
    "accountId": 101356886,
    "name": "GH",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 2586976,
  "teamName": "OG",
  "players": [
   {
    "accountId": 355168766,
    "name": "Natsumi",
    "pos": 1
   },
   {
    "accountId": 324277900,
    "name": "Yopaj-",
    "pos": 2
   },
   {
    "accountId": 132309493,
    "name": "Raven",
    "pos": 3
   },
   {
    "accountId": 155494381,
    "name": "TIMS",
    "pos": 4
   },
   {
    "accountId": 100594231,
    "name": "skem",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 9247354,
  "teamName": "Team Falcons",
  "players": [
   {
    "accountId": 100058342,
    "name": "skiter",
    "pos": 1
   },
   {
    "accountId": 898455820,
    "name": "Malr1ne",
    "pos": 2
   },
   {
    "accountId": 183719386,
    "name": "AMMAR_THE_F",
    "pos": 3
   },
   {
    "accountId": 25907144,
    "name": "Cr1t-",
    "pos": 4
   },
   {
    "accountId": 10366616,
    "name": "Sneyking",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 2163,
  "teamName": "Team Liquid",
  "players": [
   {
    "accountId": 152962063,
    "name": "m1CKe",
    "pos": 1
   },
   {
    "accountId": 201358612,
    "name": "Nisha",
    "pos": 2
   },
   {
    "accountId": 97590558,
    "name": "Ace ♠",
    "pos": 3
   },
   {
    "accountId": 77490514,
    "name": "Boxi",
    "pos": 4
   },
   {
    "accountId": 16497807,
    "name": "tOfu",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 5017210,
  "teamName": "Team Resilience",
  "players": [
   {
    "accountId": 170896543,
    "name": "YSR-04E",
    "pos": 1
   },
   {
    "accountId": 315272623,
    "name": "Echozz",
    "pos": 2
   },
   {
    "accountId": 145957968,
    "name": "niu",
    "pos": 3
   },
   {
    "accountId": 150961567,
    "name": "planet",
    "pos": 4
   },
   {
    "accountId": 249835593,
    "name": "zzq",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 7119388,
  "teamName": "Team Spirit",
  "players": [
   {
    "accountId": 321580662,
    "name": "Yatoro",
    "pos": 1
   },
   {
    "accountId": 106305042,
    "name": "Larl",
    "pos": 2
   },
   {
    "accountId": 302214028,
    "name": "Collapse",
    "pos": 3
   },
   {
    "accountId": 218231587,
    "name": "not_me",
    "pos": 4
   },
   {
    "accountId": 847565596,
    "name": "rue",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 9572001,
  "teamName": "TEAM VISION",
  "players": [
   {
    "accountId": 1044002267,
    "name": "Satanic",
    "pos": 1
   },
   {
    "accountId": 106573901,
    "name": "No[o]ne-",
    "pos": 2
   },
   {
    "accountId": 195108598,
    "name": "Noticed",
    "pos": 3
   },
   {
    "accountId": 164199202,
    "name": "9Class",
    "pos": 4
   },
   {
    "accountId": 73401082,
    "name": "Dukalis",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 9823272,
  "teamName": "Team Yandex",
  "players": [
   {
    "accountId": 171262902,
    "name": "医者watson`",
    "pos": 1
   },
   {
    "accountId": 312436974,
    "name": "CHIRA_JUNIOR",
    "pos": 2
   },
   {
    "accountId": 56351509,
    "name": "DM",
    "pos": 3
   },
   {
    "accountId": 103735745,
    "name": "Saksa",
    "pos": 4
   },
   {
    "accountId": 93817671,
    "name": "Maladych",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 726228,
  "teamName": "Vici Gaming",
  "players": [
   {
    "accountId": 320252024,
    "name": "shiro",
    "pos": 1
   },
   {
    "accountId": 137129583,
    "name": "Xm",
    "pos": 2
   },
   {
    "accountId": 118134220,
    "name": "Bach",
    "pos": 3
   },
   {
    "accountId": 157475523,
    "name": "XinQ",
    "pos": 4
   },
   {
    "accountId": 111114687,
    "name": "y`",
    "pos": 5
   }
  ]
 },
 {
  "teamId": 8261500,
  "teamName": "Xtreme Gaming",
  "players": [
   {
    "accountId": 898754153,
    "name": "Ame",
    "pos": 1
   },
   {
    "accountId": 173978074,
    "name": "NothingToSay",
    "pos": 2
   },
   {
    "accountId": 129958758,
    "name": "Xxs",
    "pos": 3
   },
   {
    "accountId": 101695162,
    "name": "fy",
    "pos": 4
   },
   {
    "accountId": 94296097,
    "name": "xNova",
    "pos": 5
   }
  ]
 }
];
